baseurl: "/"
languageCode: "et-ee"
title: "René Piik"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Sisu
      url: ""
      weight: 1
    - name: Minust
      url: "minust/"
      weight: 2
      # - name: Kategooriad
      #   url: "categories/"
      #   weight: 3
      # - name: RSS
      #   url: "index.xml"

params:
  description: "René koduleht."
  footer: "&copy; René Piik 2021 | [Twitter](https://twitter.com/renepiik) <br> Hugo teema autor on [Yihui Xie](https://yihui.org)"

markup:
  goldmark:
    renderer:
      unsafe: true
