baseurl: "/"
languageCode: "en-us"
title: "René Piik"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: RSS
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; René Piik 2021 | [Twitter](https://twitter.com/renepiik) <br> Theme by [Yihui Xie](https://yihui.org)"

markup:
  goldmark:
    renderer:
      unsafe: true
